version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    container_name: api
    ports:
      - "80:4001"
    networks:
      - backend
    depends_on:
      - redis
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:14.5
    container_name: db
    env_file:
      - .env
    restart: always
    ports:
      - "5433:5433" 
    networks:
      - backend
    volumes: 
      - db:/var/lib/postgresql/data
  redis:
    image: redis:7.0
    container_name: redis
    env_file:
      - .env
    networks:
      - backend
    volumes: 
      - cache:/data  

networks:
  backend:
    driver: bridge
volumes:
  db:
    driver: local
  cache:
    driver: local  

